-- ADMS Braga v93 — catálogo público e encomendas da ADMS Store

create table if not exists public.store_products (
  id uuid primary key default gen_random_uuid(),
  nome text not null check (char_length(nome) between 2 and 120),
  descricao text,
  categoria text not null default 'Artigos cristãos',
  preco numeric(10,2) not null check (preco >= 0),
  imagem_url text,
  stock integer not null default 0 check (stock >= 0),
  ativo boolean not null default true,
  ordem integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_orders (
  id uuid primary key default gen_random_uuid(),
  referencia text not null unique,
  cliente_nome text not null,
  cliente_telefone text not null,
  cliente_email text,
  entrega text not null default 'levantamento' check (entrega in ('levantamento','contacto')),
  observacoes text,
  total numeric(10,2) not null check (total >= 0),
  estado text not null default 'novo' check (estado in ('novo','confirmado','pago','preparacao','concluido','cancelado')),
  rgpd_aceite_em timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.store_orders(id) on delete cascade,
  produto_id uuid references public.store_products(id) on delete set null,
  produto_nome text not null,
  preco_unitario numeric(10,2) not null check (preco_unitario >= 0),
  quantidade integer not null check (quantidade between 1 and 50),
  subtotal numeric(10,2) generated always as (preco_unitario * quantidade) stored
);

create index if not exists store_products_public_idx on public.store_products (ativo, ordem, nome);
create index if not exists store_orders_created_idx on public.store_orders (created_at desc);
create index if not exists store_order_items_order_idx on public.store_order_items (order_id);

alter table public.store_products enable row level security;
alter table public.store_orders enable row level security;
alter table public.store_order_items enable row level security;

drop policy if exists "store_products_public_read_v93" on public.store_products;
create policy "store_products_public_read_v93" on public.store_products
for select to anon, authenticated using (ativo = true);

drop policy if exists "store_products_admin_all_v93" on public.store_products;
create policy "store_products_admin_all_v93" on public.store_products
for all to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.ativo=true and (p.role in ('master','pastor','secretaria') or lower(coalesce(p.cargo,'')) like '%secretar%')))
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.ativo=true and (p.role in ('master','pastor','secretaria') or lower(coalesce(p.cargo,'')) like '%secretar%')));

drop policy if exists "store_orders_admin_all_v93" on public.store_orders;
create policy "store_orders_admin_all_v93" on public.store_orders
for all to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.ativo=true and (p.role in ('master','pastor','secretaria') or lower(coalesce(p.cargo,'')) like '%secretar%')))
with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.ativo=true and (p.role in ('master','pastor','secretaria') or lower(coalesce(p.cargo,'')) like '%secretar%')));

drop policy if exists "store_order_items_admin_read_v93" on public.store_order_items;
create policy "store_order_items_admin_read_v93" on public.store_order_items
for select to authenticated
using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.ativo=true and (p.role in ('master','pastor','secretaria') or lower(coalesce(p.cargo,'')) like '%secretar%')));

revoke all on public.store_products, public.store_orders, public.store_order_items from anon, authenticated;
grant select on public.store_products to anon, authenticated;
grant insert, update, delete on public.store_products to authenticated;
grant select, update on public.store_orders to authenticated;
grant select on public.store_order_items to authenticated;

insert into public.store_products (nome,descricao,categoria,preco,stock,ordem)
select * from (values
  ('Bíblia Sagrada','Edição para leitura, estudo e presente.','Bíblias e livros',25.00,10,10),
  ('T-shirt ADMS Braga','T-shirt cristã da congregação. Tamanhos sujeitos a confirmação.','Vestuário',18.00,20,20),
  ('Caneca Fé e Comunhão','Caneca temática para uso pessoal ou oferta.','Presentes',10.00,15,30)
) as seed(nome,descricao,categoria,preco,stock,ordem)
where not exists (select 1 from public.store_products);

